#Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/chamados
spring.datasource.username=Lucas
spring.datasource.password=dev123

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=3511229a89282ef183fab70cf5e58092465ebf9537fcce60941a7b173c16b54c

