#Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/chamados
spring.datasource.username=Lucas
spring.datasource.password=dev123

#JPA Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

